[build-system]
# https://numpy.org/devdocs/user/depending_on_numpy.html?highlight=mean#build-time-dependency
requires = ["Cython", "oldest-supported-numpy", "setuptools", "wheel"]

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::skbio.util.SkbioWarning",
]
